### PR TITLE
Bs4 compatibility

### PR DESCRIPTION
**Pull request by hoaaah**
This PR will add compatibility for this GII to create a crud form compatible with BS4.

### CODE REVIEW

**Comment by ilyosdev** [comment]
plz merge it

**Comment by hoaaah** [comment]
Because this repository seems abandoned, I created https://github.com/hoaaah/yii2-ajaxcrud-bs4 . If this PR approved I will delete it.

**Comment by ingmanuelcaicedo** [comment]
> Because this repository seems abandoned, I created https://github.com/hoaaah/yii2-ajaxcrud-bs4 . If this PR approved I will delete it.

Thanks, That worked for me, but I have a problem now, I can't search anything now. Do you have the same problem as well??

**Comment by hoaaah** [comment]
> 
> 
> > Because this repository seems abandoned, I created https://github.com/hoaaah/yii2-ajaxcrud-bs4 . If this PR approved I will delete it.
> 
> Thanks, That worked for me, but I have a problem now, I can't search anything now. Do you have the same problem as well??

I don't know. Since you didn't give any clue about your code or case, I can't reproduce the issue. 
This repo is abandoned, please create issue in my repository instead.

**Pull request merged**
